---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: centos-7.4

suites:
  - name: default
    run_list:
      - recipe[virtualbox::default]
    attributes:
    verifier:
      inspec_tests:
        - test/smoke/default
